<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>local.sefast</groupId>
  <artifactId>sefast-teavm</artifactId>
  <version>1.0-SNAPSHOT</version>

  <properties>
    <maven.compiler.release>17</maven.compiler.release>
    <project.build.sourceEncoding>windows-1252</project.build.sourceEncoding>
    <teavm.version>0.12.3</teavm.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.teavm</groupId>
      <artifactId>teavm-classlib</artifactId>
      <version>${teavm.version}</version>
    </dependency>
    <dependency>
      <groupId>org.teavm</groupId>
      <artifactId>teavm-jso-apis</artifactId>
      <version>${teavm.version}</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <version>3.6.1</version>
        <executions>
          <execution>
            <id>add-se-source</id>
            <phase>generate-sources</phase>
            <goals><goal>add-source</goal></goals>
            <configuration>
              <sources>
                <source>${project.basedir}/../../SukakuExplainer</source>
              </sources>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.teavm</groupId>
        <artifactId>teavm-maven-plugin</artifactId>
        <version>${teavm.version}</version>
        <executions>
          <execution>
            <id>compile-javascript</id>
            <goals><goal>compile</goal></goals>
          </execution>
        </executions>
        <configuration>
          <mainClass>sefast.teavm.SeFastEntry</mainClass>
          <targetDirectory>${project.basedir}/../build/teavm</targetDirectory>
          <targetFileName>sefast-java.js</targetFileName>
          <optimizationLevel>ADVANCED</optimizationLevel>
          <minifying>true</minifying>
          <assertionsRemoved>true</assertionsRemoved>
          <sourceMapsGenerated>false</sourceMapsGenerated>
          <debugInformationGenerated>false</debugInformationGenerated>
        </configuration>
      </plugin>
    </plugins>
  </build>
  <profiles>
    <profile>
      <id>wasm</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.teavm</groupId>
            <artifactId>teavm-maven-plugin</artifactId>
            <version>${teavm.version}</version>
            <configuration>
              <mainClass>sefast.teavm.SeFastEntry</mainClass>
              <targetType>WEBASSEMBLY</targetType>
              <targetDirectory>${project.basedir}/../build/teavm-wasm</targetDirectory>
              <targetFileName>sefast-java.wasm</targetFileName>
              <optimizationLevel>ADVANCED</optimizationLevel>
              <minHeapSize>64</minHeapSize>
              <maxHeapSize>1024</maxHeapSize>
              <minifying>true</minifying>
              <assertionsRemoved>true</assertionsRemoved>
              <sourceMapsGenerated>false</sourceMapsGenerated>
              <debugInformationGenerated>false</debugInformationGenerated>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>c</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.teavm</groupId>
            <artifactId>teavm-maven-plugin</artifactId>
            <version>${teavm.version}</version>
            <configuration>
              <mainClass>sefast.teavm.SeFastEntry</mainClass>
              <targetType>C</targetType>
              <targetDirectory>${project.basedir}/../build/teavm-c</targetDirectory>
              <targetFileName>sefast-java.c</targetFileName>
              <optimizationLevel>ADVANCED</optimizationLevel>
              <minifying>true</minifying>
              <assertionsRemoved>true</assertionsRemoved>
              <sourceMapsGenerated>false</sourceMapsGenerated>
              <debugInformationGenerated>false</debugInformationGenerated>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>wasmgc</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.teavm</groupId>
            <artifactId>teavm-maven-plugin</artifactId>
            <version>${teavm.version}</version>
            <configuration>
              <mainClass>sefast.teavm.SeFastEntry</mainClass>
              <targetType>WEBASSEMBLY_GC</targetType>
              <targetDirectory>${project.basedir}/../build/teavm-wasmgc</targetDirectory>
              <targetFileName>sefast-java.wasm</targetFileName>
              <optimizationLevel>ADVANCED</optimizationLevel>
              <minifying>true</minifying>
              <assertionsRemoved>true</assertionsRemoved>
              <sourceMapsGenerated>false</sourceMapsGenerated>
              <debugInformationGenerated>false</debugInformationGenerated>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
